name: Terraform Validate and Test
on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
      - master

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6.0.2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v4.0.0

      - name: Terraform Init
        run: terraform init -backend=false

      - name: Terraform Format Check
        run: terraform fmt -recursive -check

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Test
        run: terraform test
